from core.env import Environment

GOOGLE_API_TOKEN = Environment("GOOGLE_API_TOKEN", "AIzaSyB0n4GW5e1lX4KDgVsgcMVMeU_LQee5YtU")
DISCORD_BOT_TOKEN = Environment("DISCORD_BOT_TOKEN", "Njc3ODYwNDA5MTQ2ODY3NzMz.XkaYuA.1y50GVjlQFHOtw7xLH2IYJO_AiQ")